### ISSUE TITLE
Want pull requests?

### ISSUE THREAD

**Issue by gunnarx** [RichiH/conference_proceedings#73]
Richi, a few questions I had, which were not answered by the README.  Of course this could be answered by sending a pull request but I'm not sure when/if I will put the work in and I may do it differently if it's only for me:
- First, do you still want pull requests?  :) Extend the library with more conferences?
- Are you interested in Linux Foundation events such as Embedded Linux Conference and any open-source conference?  Current content looks like more hard-core Free Software events are favored. ;)   Are there some criteria for what constitutes conferences of interest?
- Are Youtube URLs acceptable or only URLs that point to real files.  (git-annex quvi support in mind, etc...)
- OK to link only the videos, and no slides or do you feel proceedings must be "complete" to be of value here.
- Free formats only, or h.264 OK if that's all that exists?
- Any other requirements you can think of...

**Comment by gunnarx** [comment]
Sorry, realized many of the questions could be answered by some grepping (found recent pulls, including youtube/mp4), etc. Anyway if you feel like commenting... would be nice. :-)

**Comment by joeyh** [comment]
gunnarx wrote:
>   • First, do you still want pull requests? :) Extend the library with more
>     conferences?

yes

>   • Are you interested in Linux Foundation events such as Embedded Linux
>     Conference and any open-source conference? Current content looks like more
>     hard-core Free Software events are favored. ;) Are there some criteria for
>     what constitutes conferences of interest?

I guess pull requests will be merged as long as they seem useful to the
kind of people who use this repository. If the subject matter drifted or
expanded too far beyond that point, we'd probaby just say "fork it".

>   • Are Youtube URLs acceptable or only URLs that point to real files.
>     (git-annex quvi support in mind, etc...)

Use git annex addurl --relaxed for youtube (and for everything, but
especially youtube).

>   • OK to link only the videos, and no slides or do you feel proceedings must
>     be "complete" to be of value here.

Slides are nice, but not required.

>   • Free formats only, or h.264 OK if that's all that exists?

Free formats preferred, but not enforced.

-- 
see shy jo

**Comment by gunnarx** [comment]
Thanks Joey & sorry for the obvious questions but I just wanted some sync up.  One reason is I almost got involved in the related debconf annex repo last August (I was in Heidelberg) but got stuck on not being a DD abd there was some access issue IIRC.  In any case Github  pull requests will make this easier.  Thanks again, and thanks for the awesome tools (using git-annex, mr, and github-backup). Closing.

**Comment by RichiH** [comment]
This is a belated "I agree with @joeyh".
